spring:
  application:
    name: inventory-management
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_management
    username: postgres
    password: pt5458
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8086
  servlet:
    context-path: /api/1.0


